### ISSUE TITLE
TypeError: argument 2 must be string, not None

### ISSUE THREAD

**Issue by ozw1z5rd** [requests/requests-kerberos#102] opened 2017-10-26 15:01 UTC
Hello all, I'm using the HDFSclient which uses this library. I keep getting this error:

```
  File "/home/xxxx.xxxx/.virtualenvs/airflow/lib/python2.7/site-packages/requests_kerberos/kerberos_.py", line 130, in generate_request_header
    gssflags=gssflags, principal=self.principal)
TypeError: argument 2 must be string, not None
```
BUT... I found that forcing an empty string allows me to use the library with no issue: 
```
 82 class HTTPKerberosAuth(AuthBase):
 83     """Attaches HTTP GSSAPI/Kerberos Authentication to the given Request
 84     object."""
 85     def __init__(
 86             self, mutual_authentication=REQUIRED,
 87             service="HTTP", delegate=False, force_preemptive=False,
 88             principal="" , hostname_override=None, sanitize_mutual_error_response=True):
 
before it was principal = None

```
So here the question: 

It is so wrong to set the principal to one empty string instead None?

**Comment by behackett** [comment] 2017-10-26 16:01
The problem is you are using [kerberos](https://pypi.python.org/pypi/kerberos) instead of [pykerberos](https://pypi.python.org/pypi/pykerberos) which doesn't have this bug. The bug has been fixed in Apple's upstream kerberos module, but the fix hasn't been released:

https://github.com/apple/ccs-pykerberos/commit/a47bac77a5d5176143c0b97d5d7f70d6417865a3

**Closed** 2017-12-07 07:07 UTC
Labels: question
