### ISSUE TITLE
unable to import looking for winkerberos I am running from Linux

### ISSUE THREAD

**Issue by ebmilleriii** [requests/requests-kerberos#112] opened 2018-03-14 15:18 UTC
----> 1 from requests_kerberos import HTTPKerberosAuth

/data/apps/Anaconda3-5.0.1/lib/python3.6/site-packages/requests_kerberos/__init__.py in <module>()
     15 import logging
     16
---> 17 from .kerberos_ import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
     18 from .exceptions import MutualAuthenticationError
     19 from .compat import NullHandler

/data/apps/Anaconda3-5.0.1/lib/python3.6/site-packages/requests_kerberos/kerberos_.py in <module>()
      2     import kerberos
      3 except ImportError:
----> 4     import winkerberos as kerberos
      5 import re
      6 import logging

ModuleNotFoundError: No module named 'winkerberos'

**Comment by behackett** [comment] 2018-03-14 15:23
This is an unfortunate side-effect of the order of the import attempts. requests-kerberos should really attempt to import winkerberos first and fallback to pykerberos to avoid this confusion.

The problem is you don't have pykerberos installed.
https://pypi.python.org/pypi/pykerberos/1.2.1

**Comment by behackett** [comment] 2018-03-14 22:25
Looks like requests-kerberos requires 1.1.8 or better, so your version should be fine. The problem appears to be you don't have pykerberos installed for the interpreter you're using.

**Comment by rahulbhanushali** [comment] 2019-07-22 10:17
Facing the same problem while deploying to AWS lambda using Zappa.
@ebmilleriii, were you able to solve this?

**Comment by jborean93** [comment] 2021-10-30 22:41
Closing as per https://github.com/requests/requests-kerberos/issues/112#issuecomment-373195401. On the upcoming `0.13.x` release the dependency for both Linux and Window has been unified to [pyspnego](https://pypi.org/project/pyspnego/) simplifying this problem going forward.

**Closed by jborean93** 2021-10-30 22:41 UTC
