### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by christophvw** [requests/requests-kerberos#148] opened 2020-03-09 10:34 UTC
Could it be that kerberos proxy authentication is not supported yet?

407 - Proxy-Authenticate', 'Proxy-Authorization

**Comment by christophvw** [comment] 2020-03-09 13:07
patch for proxy-support

TODO:
-host should be set to the proxy server (currently you have to use hostname_override)
-fix urlib3 HTTPS proxy support


`--- C:/Users/wittich/Desktop/kerberos_.py	Mo  9. Mrz 14:04:14 2020
+++ C:/Users/wittich/Desktop/kerberos_proxy.py	Mo  9. Mrz 14:04:52 2020
@@ -88 +88,4 @@ def _negotiate_value(response):
-    authreq = response.headers.get('www-authenticate', None)
+    if response.status_code == 401:
+        authreq = response.headers.get('www-authenticate', None)
+    else:
+        authreq = response.headers.get('proxy-authenticate', None)
@@ -266,3 +269,8 @@ class HTTPKerberosAuth(AuthBase):
-        log.debug("authenticate_user(): Authorization header: {0}".format(
-            auth_header))
-        response.request.headers['Authorization'] = auth_header
+        if response.status_code == 401:
+            log.debug("authenticate_user(): Authorization header: {0}".format(
+                auth_header))
+            response.request.headers['Authorization'] = auth_header
+        elif response.status_code == 407:
+            log.debug("authenticate_user(): Proxy-Authorization header: {0}".format(
+                auth_header))
+            response.request.headers['Proxy-Authorization'] = auth_header
@@ -293,0 +302,13 @@ class HTTPKerberosAuth(AuthBase):
+    def handle_407(self, response, **kwargs):
+        """Handles 407's, attempts to use gssapi/kerberos authentication"""
+
+        log.debug("handle_407(): Handling: 407")
+        if _negotiate_value(response) is not None:
+            _r = self.authenticate_user(response, **kwargs)
+            log.debug("handle_407(): returning {0}".format(_r))
+            return _r
+        else:
+            log.debug("handle_407(): Kerberos is not supported")
+            log.debug("handle_407(): returning {0}".format(response))
+            return response
+
@@ -376,0 +398 @@ class HTTPKerberosAuth(AuthBase):
+        num_407s = kwargs.pop('num_407s', 0)
@@ -409,0 +432,13 @@ class HTTPKerberosAuth(AuthBase):
+        elif response.status_code == 407 and num_407s < 2:
+            # 407 Unauthorized. Handle it, and if it still comes back as 401,
+            # that means authentication failed.
+            _r = self.handle_407(response, **kwargs)
+            log.debug("handle_response(): returning %s", _r)
+            log.debug("handle_response() has seen %d 407 responses", num_407s)
+            num_407s += 1
+            return self.handle_response(_r, num_407s=num_407s, **kwargs)
+        elif response.status_code == 407 and num_407s >= 2:
+            # Still receiving 407 responses after attempting to handle them.
+            # Authentication has failed. Return the 407 response.
+            log.debug("handle_response(): returning 407 %s", response)
+            return response
`

**Comment by christophvw** [comment] 2020-03-09 13:09
diff as text file

[kerberos_.txt](https://github.com/requests/requests-kerberos/files/4306706/kerberos_.txt)

**Comment by enzolis** [comment] 2020-03-11 15:23
Thanks for providing this patch. I am using a company proxy which asks for authentication via Kerberos.

I changed your code slightly to check for a set proxy in case of 407 during authenticate_user to use this as the host name to get the service ticket for.

[kerberos_proxy.txt](https://github.com/requests/requests-kerberos/files/4319075/kerberos_proxy.txt)

**Comment by pradyunsg** [comment] 2020-04-06 16:30
Please consider filing [pull requests](https://help.github.com/en/github/getting-started-with-github/github-glossary#pull-request) instead of attaching patches as attachments to comments.

**Comment by enzolis** [comment] 2020-04-07 10:05
Yes, you are right. Lets follow up here: https://github.com/requests/requests-kerberos/pull/149

**Comment by ManWalkingBy** [comment] 2020-04-15 18:40
I think that this point:

> fix urlib3 HTTPS proxy support

 is the main point of yourTODO-list. If it were possible to solve the problem with urllib3 (or rather, the problem with the function _tunnel of module httplib/http.client that raises an OSError if it does not receive the necessary authentication data), then it would be possible to quickly implement authentication with a proxy server for all other types of authentication (digest, NTLM). But for now, despite the many requests similar to this (there was already a similar request for this library too - #83 ), this problem has not been resolved. We can only use various workarounds. For example, if you require preempetive authentication, you can use this approach (I mentioned it in #83 ):
```
import requests
from requests_kerberos import HTTPKerberosAuth
from urllib3.util import parse_url

class HTTPAdapterWithProxyKerberosAuth(requests.adapters.HTTPAdapter):
    def proxy_headers(self, proxy):
        headers = {}
        auth = HTTPKerberosAuth()
        negotiate_details = auth.generate_request_header(None, parse_url(proxy).host, is_preemptive=True)
        headers['Proxy-Authorization'] = negotiate_details
        return headers

session = requests.Session()
session.proxies = {'http': 'http://yourproxy:proxyport', 'https': 'http://yourproxy:proxyport'}
session.mount('https://', HTTPAdapterWithProxyKerberosAuth())

response = session.get("https://www.google.com/")
```
This approach repeats what happens in the case of Basic authentication, which the `requests ` supports. We prepare authentication data in advance for sending to the `_tunnel`, so it does not raise an error. This code works for me, maybe it will come in handy for you too.
If we consider non-preempetive authentication, it might be enough to rewrite the method `proxy_headers` like this:
```
class HTTPAdapterWithProxyKerberosAuth(requests.adapters.HTTPAdapter):
    def proxy_headers(self, proxy):
        headers = {}
        proxy_response = requests.get(proxy, auth=HTTPKerberosAuth())
        headers['Proxy-Authorization'] = response.request.headers['Authorization']
        return headers
```
But I'm not sure it needs to be tested.

**Comment by christophvw** [comment] 2021-04-22 13:51
https://github.com/urllib3/urllib3/blob/main/CHANGES.rst
1.26.0 (2020-11-10)
Added support for HTTPS proxies contacting HTTPS servers (Pull #1923, Pull #1806)


The underlying problem should be fixed now.
Any update to get this merged?

**Comment by jborean93** [comment] 2021-10-30 22:59
Duplicate of https://github.com/requests/requests-kerberos/issues/83

**Closed by jborean93** 2021-10-30 22:59 UTC
