### ISSUE TITLE
Mutual authentication unavailable on 403 response

### ISSUE THREAD

**Issue by mdeguzis** [requests/requests-kerberos#90] opened 2017-02-16 13:58 UTC
OS: RHEL 7
Package version: python-kerberos.x86_64    1.1-15.el7

I have had great suggest using the get request and this project:

```
url = "http://" + HDFS_HOST + ":" + HDFS_PORT + "/webhdfs/v1" + hdfs_path + op 
resp = requests.get(url, auth=requests_kerberos.HTTPKerberosAuth())
```

However, I am struggling to make use of put with this authentication library. I absolutely have the rights to do even this simple test to my own /user directory on HDFS, and that has always worked with a python subprocess, but I cannot get this to work with this. I cannot specify the principal, as that doesn't seem supported under our environment.

```
2017-02-16 08:39:53,462 - ERROR - handle_other(): Mutual authentication unavailable on 403 response
2017-02-16 08:39:53,463 - ERROR - Unable to transfer file /home/mtdeguzis/testfile.txt to HDF
```

Log snippet (deidentified): https://gist.github.com/mdeguzis/af2b4b945b13e8f4ff57dc6979359157

**Comment by rbcarson** [comment] 2017-02-16 22:59
Have you had any success with this Kerberos-authenticated `PUT` using other clients, such as curl or Chrome? I'm not yet convinced that this is a requests-kerberos issue instead of a permissions issue.

**Comment by mdeguzis** [comment] 2017-02-17 01:20
Ok, I will give that a try in the morning.

**Comment by mdeguzis** [comment] 2017-02-20 21:21
I can make the curl request just fine (with redirect), but not using requests.

```
curl --negotiate -u : -X PUT -T /path/testfile.txt "http://HOST:PORT/webhdfs/v1/user/<USER>/testfile.txt?op=CREATE&data=true&overwrite=true&permission=755"
```

With python:

url:
```
http://HOST:PORT/webhdfs/v1/user/<USER>/testfile2.txt?op=CREATE&data=true&overwrite=true&permission=755
```

Command:
```
requests.put('http://HOST:PORT/webhdfs/v1/user/<USER>/testfile2.txt?op=CREATE&data=true&overwrite=true&permission=755', data='/home/<USER>/testfile2.txt', auth=requests_kerberos.HTTPKerberosAuth())
```

Output

```
Traceback (most recent call last):                                                                                                                                                                                                      [0/0]
  File "audit-tool.py", line 1158, in <module>
    webhdfs_copy_to_hdfs(KERBEROS_ENABLED, HDFS_HOST, username, password, log_filename, log_dest_hdfs, HDFS_PORT)
  File "audit-tool.py", line 958, in webhdfs_copy_to_hdfs
    resp = requests.put(url, data=open(local_file, 'r'), auth=requests_kerberos.HTTPKerberosAuth())
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 121, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 602, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 582, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "build/bdist.linux-x86_64/egg/requests_kerberos/kerberos_.py", line 279, in handle_response
  File "build/bdist.linux-x86_64/egg/requests_kerberos/kerberos_.py", line 224, in handle_other
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [201]>
```

It's probably my ineptitude, but i'm unsure why I can make this fully work with curl then.

**Comment by rbcarson** [comment] 2017-02-20 22:00
Your curl request will actually upload a file, but your `requests.put(url, data='/home/<USER>/testfile2.txt')` will make a PUT request with the string `/home/<USER>/testfile2.txt` as the body. Is this a bug?

I see that in your latest log you apparently get a 201 response with Requests, instead of 403. Was something uploaded successfully then?

I don't know your environment, but you could turn off mutual authentication in requests-kerberos, if that's acceptable for your scenario. Maybe curl succeeds if it's not doing that step.

**Comment by mdeguzis** [comment] 2017-02-20 23:53
> Your curl request will actually upload a file, but your requests.put(url, data='/home/<USER>/testfile2.txt') will make a PUT request with the string /home/<USER>/testfile2.txt as the body. Is this a bug?

It should just be pushing testfile2.txt to that HDFS location/filename. Once I fixed up the code a bit to upload the "shortname" as part of the url, that changed:

Here is that code: [gist](https://gist.github.com/mdeguzis/1e10d285e5f2e2125f67f9653e735930)

```
requests.put('http://HOST:PORT/webhdfs/v1/user/<USER>/testfile2.txt?op=CREATE&data=true&overwrite=true&permission=755', data='/home/<USER>/testfile2.txt', auth=requests_kerberos.HTTPKerberosAuth())
```

**Comment by mdeguzis** [comment] 2017-02-21 13:07
Ok, so it works as me to my directory, just not the target directory for our department. Probably a rights issue. I apologize.

**Comment by rbcarson** [comment] 2017-02-21 18:23
The `principal` and `force_preemptive` keywords on `HTTPKerberosAuth` was added at various points last year, so it sounds like you're on an old version.

**Comment by mdeguzis** [comment] 2017-03-30 17:11
Still struggling with this. I am using the latest PyPi version, but I have also tried master tree here.

**Comment by rbcarson** [comment] 2017-03-30 17:14
What is the problem - `principal` and `force_preemptive` keywords still unrecognized?

**Comment by mdeguzis** [comment] 2017-03-30 17:20
No matter what I do, I cannot get past a 403 here. I am testing to make sure I also kinit has our "super user" before the request is made.

```
subprocess.call(['sudo', '-u', 'hdfs', 'kinit', '-kt', '/etc/security/keytabs/hdfs-keytab', 'hdfs-hdp_prod@COMPANY.COM']

resp = requests.get(url, auth=requests_kerberos.HTTPKerberosAuth(principal="hdfs-hdp_prod@COMPAN.COM"))
```

https://gist.github.com/mdeguzis/dde92a882618fc1e888b3eedfbe3220c

**Comment by rbcarson** [comment] 2017-03-30 17:41
Kerberos and HDFS happens to be something I'm tinkering with, though I'm not actually a user of Hadoop. Could you provide instructions on how to set up an HDFS server like yours, so that I may reproduce this scenario? It'd be very valuable.

Your example first calls kinit with `-kt`, and the error from the trace is `Can't find client principal hdfs-hdp_prod@COMPANY.COM in cache collection`. Maybe requests-kerberos only uses the default keytab location? I'm just wildly guessing.

**Comment by mdeguzis** [comment] 2017-03-30 17:44
I can't divulge that kind of info on a low level. The best thing to is setup a VM with a [sandbox](https://hortonworks.com/products/sandbox/). This should give you an environment you can work with. If you need help, let me know.

> Maybe requests-kerberos only uses the default keytab location? I'm just wildly guessing.

Maybe? In any case, I am very open to helping testing WEBHDFS/HDFS here. Using a subprocess is very slow. I suppose I could try a subprocess with a working curl command (for speed at least).

**Comment by rbcarson** [comment] 2017-03-30 20:51
I believe we've been wrangling with the Cloudera VM. Maybe we'll have an easier time with Sandbox. It's a bit of a pain point because all we care about is HDFS, and not all the other stuff that comes with it.

Please try using the default keytab, so that the Kerberos library on the Python side can pick up your cached credentials. Hopefully that'll work.

Interestingly, [hdfscli supports Kerberos](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.ext.kerberos.KerberosClient) using requests-kerberos but defaults to optional mutual authentication.

**Comment by mrajan200** [comment] 2017-11-29 20:58
for following curl command 
`curl --negotiate -u :  -H "X-Requested-By:ambari" -i -X GET  http://hostnamefornamenode:50070/jmx?qry=Hadoop:service=NameNode,name=FSNamesystem `

I used following code in python 

```
import requests
from requests_kerberos import HTTPKerberosAuth
headers = {
    'X-Requested-By': 'ambari',
}
params = (
    ('qry', 'Hadoop:service=NameNode,name=FSNamesystem'),
)
res = requests.get('http://hostnamefornamenode:50070/jmx', headers=headers, params=params, auth=HTTPKerberosAuth())
print res.json()

```

**Comment by mdeguzis** [comment] 2017-12-02 02:19
Thanks @mrajan200 , i'll revisit this for my needs. Having this auth type work will be great, even though I was able to work around, if you call it that, but requesting auth via user/pass via our Knox gateway on Hadoop.

**Comment by jborean93** [comment] 2021-10-30 22:50
Closing due to the age of the ticket, at a brief glance mutual auth won't work on a 403 response because there is no server token to process.

**Closed by jborean93** 2021-10-30 22:50 UTC
